# -*- coding: utf-8 -*-
"""Text_preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199oNpaTrr9BFg0bheB2EP6SyMM9iQ6ez
"""

import nltk
nltk.download('all')

def tokenization(cropus,sentences=True,words=True):
  paragraph=cropus
  if sentences and words:
    s=nltk.sent_tokenize(paragraph)
    w=nltk.word_tokenize(paragraph)
    return s,w
  elif sentences:
    s=nltk.sent_tokenize(paragraph)
    return s
  elif words:
    w=nltk.word_tokenize(paragraph)
    return w

text='Provisions for the formation of the union territory of Jammu and Kashmir were contained within the Jammu and Kashmir Reorganisation Act, 2019, which was passed by both houses of the Parliament of India in August 2019. The act re-constituted the former state of Jammu and Kashmir into two union territories, Jammu and Kashmir and Ladakh, with effect from 31 October 2019'

tokenization(text,True,False)

tokenization(text,False,True)

tokenization(text,True,True)

from nltk.corpus import stopwords
def remove_stopwords(corpus,token=True):
  w=corpus
  if token:
    w=tokenization(corpus,False,True)
  w=[w for w in w if w not in set(stopwords.words('english'))]
  return w

remove_stopwords(text,True)

from nltk.stem import PorterStemmer
def stemming(corpus,token=True):
  w=corpus
  if token:
    w=tokenization(corpus,False,True)
  w=[PorterStemmer().stem(w) for w in w]
  return w

stemming(text,True)

x=tokenization(text,False,True)
x=remove_stopwords(x,False)
x=stemming(x,False)
print(x)

from nltk.stem import WordNetLemmatizer
def lemmatization(corpus,token=True):
  w=corpus
  if token:
    w=tokenization(w,False,True)
  w=[WordNetLemmatizer().lemmatize(w) for w in w]
  return w

lemmatization(text,True)

lemmatization(x,False)

